name: EdgeConv Tapeout

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: efabless/openlane2:latest
      options: --user root
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Run OpenLane2
        working-directory: ./openlane
        run: |
          python3 -m openlane \
            --flow Classic \
            --config config_typical.json
      
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: results
          path: runs/**/final/*
